spring:
  profiles:
    include: oauth

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
      url: jdbc:h2:mem:testdb;MODE=MYSQL

  session:
    store-type: jdbc


  mustache:
    suffix: .mustache
    prefix: classpath:/templates/